### ISSUE TITLE
Can you describe the function's function?

### ISSUE THREAD

**Issue by starsight** [fixxxxxxer/GPIOProcessorPython#1]
hello, i am new in dragonboard. i want to use your rep with my demo.
i try to use your test.py, but i failed. i connect pin 1(GND) and 6(GPIO out) with LED.  i think that i can't understand your pin name. So, can you do little explanation to describe pin name? 
thank you very much.

**Comment by fixxxxxxer** [comment]
Have you tried using any of the other functional GPIO libraries available for the DB410c?

i.e. libsoc and libmraa?

I would suggest checking out this instruction set out. Follow the beginner instructions to get your libraries set up, then proceed to the examples section to try some stuff out.

https://github.com/96boards/documentation/tree/master/ConsumerEdition/CE-Extras/GPIO

**Comment by starsight** [comment]
@sdrobertw Great! Thank you! I use the libsoc repo to control GPIO successfully! Really thank you!
